info:
  project:
    name: video-manager

server:
  port: 8080
  shutdown: graceful

management:
  server:
    port: 8081
  info.git.mode: full
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  application:
    name: video-manager

  config:
    import: optional:file:.env[.properties]

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      fail_on_empty_beans: false
      write_dates_as_timestamps: false
    property-naming-strategy: SNAKE_CASE

  flyway:
    enabled: true
    schemas: video_manager
    url: ${FLYWAY_URL}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: classpath:/db/migration
    validate-on-migrate: true

  main:
    web-application-type: reactive

  r2dbc:
    driver: postgresql
    name: video-manager
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    pool:
      initial-size: 2
      max-size: 4
      max-life-time: 30m
      validation-query: SELECT 1

  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 10MB
    enabled: true
  webflux:
    multipart:
      max-in-memory-size: 10MB

digital-ocean:
  spaces:
    region: us-east-1
    credentials:
      access-key: ${DO_ACCESS_KEY}
      secret-key: ${DO_SECRET_KEY}
    endpoint: https://nyc3.digitaloceanspaces.com
    bucket: soat7-video-manager
