info:
  project:
    name: video-manager

logging:
  level:
    org.springframework.r2dbc: error
    org.springframework.web.client: debug
    io.github.soat7.videomanager: info

server:
  port: 8080
  shutdown: graceful

management:
  server:
    port: 8081
  info.git.mode: full
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
    access:
      default: unrestricted
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  application:
    name: video-manager

  config:
    import: optional:file:.env[.properties]

  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      fail_on_empty_beans: false
      write_dates_as_timestamps: false
    property-naming-strategy: SNAKE_CASE

  flyway:
    enabled: true
    schemas: video_manager
    url: ${FLYWAY_URL}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: classpath:/db/migration
    validate-on-migrate: true

  main:
    web-application-type: reactive

  r2dbc:
    driver: postgresql
    name: video-manager
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    pool:
      initial-size: 2
      max-size: 4
      max-life-time: 30m
      validation-query: SELECT 1

  servlet.multipart:
    max-file-size: 30MB
    max-request-size: 30MB
    enabled: true
  webflux:
    multipart:
      max-in-memory-size: 30MB

digital-ocean:
  spaces:
    region: us-east-1
    credentials:
      access-key: ${DO_ACCESS_KEY:TEST}
      secret-key: ${DO_SECRET_KEY:TEST}
    endpoint: https://nyc3.digitaloceanspaces.com
    bucket:
      name: soat7-video-manager
      path: videos
messaging:
  topics:
    video-pending: video.pending
    video-processing: video.processing
    video-completed: video.completed
    video-error: video.error
  group: video-manager

nats:
  spring:
    server: ${NATS_SERVERS:nats://localhost:4222}
